-- NAS Media Index schema

CREATE TABLE scan_runs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    started_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    finished_at TIMESTAMPTZ,
    root TEXT NOT NULL,
    files_seen BIGINT NOT NULL DEFAULT 0,
    files_changed BIGINT NOT NULL DEFAULT 0
);

CREATE TABLE files (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    root TEXT NOT NULL,
    rel_path TEXT NOT NULL,
    abs_path TEXT NOT NULL UNIQUE,
    size_bytes BIGINT NOT NULL,
    mtime TIMESTAMPTZ NOT NULL,
    sha256 TEXT,
    last_seen_run_id BIGINT REFERENCES scan_runs(id)
);

CREATE INDEX idx_files_sha256 ON files(sha256);
CREATE INDEX idx_files_root ON files(root);
CREATE INDEX idx_files_mtime ON files(mtime);
